# Generated by Django 5.1.5 on 2025-01-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_record_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="number",
            field=models.CharField(max_length=15),
        ),
    ]
