# Generated by Django 5.1.5 on 2025-01-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_record_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
