# Generated by Django 5.1.5 on 2025-01-16 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_record_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="record",
            name="time",
        ),
    ]
