# Generated by Django 5.1.5 on 2025-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_remove_agent_assigned_phone_number_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=models.CharField(max_length=15),
        ),
    ]
