# Generated by Django 5.1.5 on 2025-01-31 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_remove_phonenumber_agent_agent_phone_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
