# Generated by Django 5.1.5 on 2025-02-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0011_record_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="phone_numbers",
            field=models.ManyToManyField(blank=True, to="myapp.phonenumber"),
        ),
    ]
